#!/usr/bin/env node

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = path.dirname(fileURLToPath(import.meta.url));

function stripLocalImportsExports(src) {
  return src
    .split('\n')
    .filter((line) => !/import .* from ['"]\.\/.*['"];?/.test(line.trim()))
    .join('\n')
    .replace(/export (class|function|async function|const)/gm, '$1')
    .replace(/export \{[^\}]*\};?\s*/gm, '');
}

const discoverClaude = stripLocalImportsExports(readFileSync(path.join(DIR, 'lib/discover-claude.mjs'), 'utf8'));
const discoverGemini = stripLocalImportsExports(readFileSync(path.join(DIR, 'lib/discover-gemini.mjs'), 'utf8'));
const discoverAntigravity = stripLocalImportsExports(readFileSync(path.join(DIR, 'lib/discover-antigravity.mjs'), 'utf8'));
const discover = stripLocalImportsExports(readFileSync(path.join(DIR, 'lib/discover.mjs'), 'utf8'));
const tui = stripLocalImportsExports(readFileSync(path.join(DIR, 'lib/tui.mjs'), 'utf8'));
const bin = stripLocalImportsExports(readFileSync(path.join(DIR, 'bin.mjs'), 'utf8'))
  .replace(/^#!.*\n/, '');

const bundleImports = `import fsSync from 'node:fs';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';`;

const tuiRewritten = tui.replace(/bfs\.watch\(/g, 'fsSync.watch(');

console.log(`#!/usr/bin/env node
// Fleet-monitor - single-file bundle, generated by build.mjs from the split
// files in lib/ and bin.mjs. Do not hand-edit; edit the source and re-run
// ./build.sh instead.

${bundleImports}

// ---- lib/discover-claude.mjs ----
${discoverClaude.replace(/import .*\n/gm, '')}

// ---- lib/discover-gemini.mjs ----
${discoverGemini.replace(/import .*\n/gm, '')}

// ---- lib/discover-antigravity.mjs ----
${discoverAntigravity.replace(/import .*\n/gm, '')}

// ---- lib/discover.mjs ----
${discover.replace(/import .*\n/gm, '')}

// ---- lib/tui.mjs ----
${tuiRewritten.replace(/import .*\n/gm, '')}

${bin}
`);
